INSERT INTO PRODUCTS (NAME, PRICE) VALUES ('Warhammer', 40000);
INSERT INTO PRODUCTS (NAME, PRICE) VALUES ('Warcraft', 3);
INSERT INTO PRODUCTS (NAME, PRICE) VALUES ('Moon', 2024);
INSERT INTO PRODUCTS (NAME, PRICE) VALUES ('Elder Scrolls', 3);
INSERT INTO PRODUCTS (NAME, PRICE) VALUES ('Gothic', 2);
